#!/usr/bin/env bash
mkdir -p bin

PROGRAM="lib/init.js"

echo "copy $PROGRAM to bin"

# ln -sf $(realpath $INDEX) bin/npx-local
(cd bin && ln -sf ../$PROGRAM npx-init)

chmod +x $PROGRAM
chmod +x -R bin
